### PR TITLE
WIP: Fix: Just start if container in stopped state

### PR DESCRIPTION
**Pull request by digitronik**
```
Error: error creating container storage: the container name "selenium_container" is already in use by "98a4551cab27f150b2f91ab5227103e3ccc6a37aae9a0c662ed049e7382bd6e8". You have to remove that container to be able t
```

### CODE REVIEW

**Review by sbulage — APPROVED** [review]
LGTM :+1:

**Comment by sbulage** [comment]
**Small Question:**

Did you cross-check the behavior on your env.?

**Comment by digitronik** [comment]
I got one more idea... to catch specific condition. moving to WIP

**Comment by digitronik** [comment]
closing as it fixed in refactor

**Pull request closed without merging**
